### ISSUE TITLE
Allow user to upload/link useful information

### ISSUE THREAD

**Issue by jfrank-summit** [autonomys/autonomys-agents#5]
User should be able to upload files or add links that will be helpful to content generation.

- [ ] Upload files during content generation
- [ ] Add links during content generation
- [ ] Persistent documents stored in Auto Drive and linked with Auto ID
